apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: ignatev/kibana-6.4.2:logtrail
        env:
        - name: CLUSTER_NAME
          value: myesdb
        - name: SERVER_DEFAULTROUTE
          value: "/app/kibana"
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
        readinessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
          - name: logtrail-config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: kibana-config
        - name: logtrail-config
          configMap:
            name: logtrail-config