kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: logging-storage
provisioner: kubernetes.io/aws-ebs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: efk-cluster
    component: elasticsearch-efk-cluster
    name: es-data
    role: data
  name: es-data-0
spec:
  storageClassName: logging-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: efk-cluster
    component: elasticsearch-efk-cluster
    name: es-master
    role: master
  name: es-master-0
spec:
  storageClassName: logging-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
