apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: logging-fluent-bit
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logging-fluent-bit
    spec:
      serviceAccountName: logging-fluent-bit
      containers:
      - name: fluent-bit
        image: "fluent/fluent-bit:0.14.4"
        imagePullPolicy: "Always"
        env:
          []

        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi

        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf

      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: logging-fluent-bit-config
